name: Terraform Apply

on:
  workflow_run:
    workflows: ["Terraform Plan"]
    branches: [main]
    types: [completed]

    
env:
  AWS_REGION: "eu-west-2"

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-apply
  cancel-in-progress: true


jobs:

# use approval gate to prevent pipeline running automatically
  gate:
    name: Approval gate
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production
    steps:

      # # Download the plan artifact produced by the triggering Plan run
      # - name: Download saved plan
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: tfplan
      #     path: ./terraform
      #     run-id: ${{ github.event.workflow_run.id }}
      #     github-token: ${{ github.token }}

      - name: Show Plan (for reviewer)
        working-directory: ./terraform
        run: terraform show -no-color tfplan | tee plan.txt

      - run: echo "Waiting for approval from ${{ github.actor }} to apply Terraformâ€¦"

  terraform:
    needs: gate
    name: Terraform Apply
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Pulls latest version of code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v5

      # Installs Terraform on the GitHub runner
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0

      # Configures AWS access by using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@9dfa9aa010133d4807cd0272ad05d3fdb5b01340
        with:
          role-to-assume: arn:aws:iam::241661649258:role/Github-actions-k8s
          role-session-name: tfapply
          aws-region: ${{ env.AWS_REGION }}

      # Download the plan artifact produced by the triggering Plan run
      - name: Download saved plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./terraform
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}


      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -input=false

      - name: Terraform Apply (exact saved plan)
        working-directory: ./terraform
        env:
          TF_VAR_hosted_zone_arn: ${{ secrets.HOSTED_ZONE_ARN }}
          TF_VAR_hosted_zone_id:     ${{ secrets.HOSTED_ZONE_ID }}
        run: terraform apply -no-color -input=false tfplan
        